import { Sparkles } from 'lucide-react'

export default function BriefingCard({ briefing }) {
  if (!briefing) return null

  const isFallback = /unavailable/i.test(briefing.provider || '')
  const isMock = briefing.provider === 'mock'
  const isSimulated = isFallback || isMock

  // Was previously a raw "[Note: gemini API call failed (404 NOT_FOUND...
  // )]" string tacked onto the end of the briefing text itself — looked
  // like a crash dump inside what's supposed to read as a clean,
  // plain-English summary. Now shown as a small labeled badge instead,
  // with the real error (if any) only in the hover tooltip — the
  // briefing text itself stays clean either way.
  const badgeClass = isSimulated
    ? 'text-amber-700 dark:text-amber-400 bg-amber-50 dark:bg-amber-500/10 border border-amber-400/40'
    : 'text-teal-700 dark:text-teal-400 bg-teal-50 dark:bg-teal-500/10 border border-teal-400/40'

  return (
    <div className="bg-paper-raised dark:bg-panel border border-teal-200 dark:border-teal-900/40 rounded-xl p-5">
      <div className="flex items-center justify-between mb-2">
        <h3 className="font-display text-sm font-medium text-ink dark:text-slate-200">AI Briefing</h3>
        <span
          title={
            isFallback
              ? (briefing.provider_error ? `Real AI call failed: ${briefing.provider_error} — showing a simulated briefing instead.` : 'The configured real provider was unavailable — showing a simulated briefing instead.')
              : isMock
                ? 'No real LLM key configured — this is a deterministic simulated briefing, not a live AI call.'
                : `Generated by a live ${briefing.provider} call.`
          }
          className={`flex items-center gap-1 text-[10px] uppercase tracking-wide px-2 py-0.5 rounded-full ${badgeClass}`}
        >
          <Sparkles size={10} />
          {isSimulated ? 'Simulated' : `Live · ${briefing.provider}`}
        </span>
      </div>
      <p className="text-xs text-slate-600 dark:text-slate-400 whitespace-pre-line leading-relaxed">
        {briefing.briefing}
      </p>
    </div>
  )
}
